version: '3.1'

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes/
      - ./wp-content/plugins:/var/www/html/wp-content/plugins/
      - ./wp-content/uploads:/var/www/html/wp-content/uploads/
    # depends_on:
    #   - mysql-server
    environment:
      WORDPRESS_DB_HOST: mysql-server
      WORDPRESS_DB_USER: atc
      WORDPRESS_DB_PASSWORD: AroundTheCorner
      WORDPRESS_DB_NAME: atc-site
      MYSQL_PORT_3306_TCP: 3306
    networks:
      - atc_default
  mysql-server:
    image: mysql:5.7.24
    container_name: mysql-wordpress
    restart: on-failure
    volumes:
      # named volume
      - mysql-data:/var/lib/mysql
      # bind mount
      - ./data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: atc-site
      MYSQL_USER: atc
      MYSQL_PASSWORD: AroundTheCorner
      MYSQL_ROOT_PASSWORD: rootpwd
    networks:
      - atc_default
  # Uncomment proxy if deploying locally and in isolation. In production, the Production Proxy container is used.
  # proxy:
  #   container_name: nginx
  #   image: nginx
  #   restart: always
  #   volumes:
  #     - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - '8090:80'
volumes: 
  mysql-data:
networks:
  atc_default:
    external:
      name: atc_default