version: '3'
services:
  api:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - /api/node_modules
      - .:/api
    depends_on:
      - service-db
    environment:
      SERVICE_HOST: api
      SERVICE_PORT: 3000
      DB_HOST: service-db
      DB_PORT: 3306
      DB_NAME: atc-service
      DB_USERNAME: atc
      DB_PWD: AroundTheCorner
  service-db:
    image: mysql:5.7.24
    container_name: service-db
    restart: on-failure
    volumes:
      # named volume
      - service-db-data:/var/lib/mysql
      # bind mount
      - ./data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: atc-service
      MYSQL_USER: atc
      MYSQL_PASSWORD: AroundTheCorner
      MYSQL_ROOT_PASSWORD: rootpwd
  rabbitmq:
    image: rabbitmq:management
    restart: on-failure
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq   
  proxy:
    container_name: atc-service-proxy
    image: nginx
    restart: always
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8091:80'
volumes: 
  service-db-data:
  rabbitmq-data:
      