version: '3'
services:
  api:
    container_name: api
    build: .
    ports: 
      - "3002:3000"
    volumes:
      - /api/node_modules
      - .:/api
    depends_on:
      - service-db
    environment:
      SERVICE_HOST: api
      SERVICE_PORT: 3000
      DB_HOST: service-db
      DB_PORT: 3306
      DB_NAME: atc-service
      DB_USERNAME: atc
      DB_PWD: AroundTheCorner
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      CDN_URL: 'https://api.aroundthecorner.store/'
    networks:
      - atc_default
  service-db:
    image: mysql:5.7.24
    container_name: service-db
    restart: on-failure
    volumes:
      # named volume
      - service-db-data:/var/lib/mysql
      # bind mount
      - ./data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: atc-service
      MYSQL_USER: atc
      MYSQL_PASSWORD: AroundTheCorner
      MYSQL_ROOT_PASSWORD: rootpwd
    networks:
      - atc_default
  proxy:
    container_name: atc-service-proxy
    image: nginx
    restart: always
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8091:80'
    networks:
      - atc_default
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: on-failure
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - atc_default
  worker:
    container_name: workers
    build: 
      context: ./server/worker
    environment:
      API_URL: api
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - api
      - rabbitmq
    networks:
      - atc_default
volumes: 
  service-db-data:
  rabbitmq-data:
networks:
  atc_default:
    external:
      name: atc_default
      