
version: '3'
services:
  proxy:
    container_name: atc-web-proxy
    image: nginx
    restart: always
    build: .
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8092:80'
      