
version: '3'
services:
  webApp:
    container_name: atc-web-proxy
    image: nginx
    restart: always
    #build: .
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
    ports:
      - '8092:80'
    networks:
      - atc_default
networks:
  atc_default:
    external:
      name: atc_default